name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # ⚠️ 如果你主分支不是 main，请改成 master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # 这是 GitHub Actions 用的，不需要你本地有 ruby

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build -s ./docs -d ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
